---

- fail: msg="You must define prezto_users_config dict in your playbook !"
  when: >
   prezto_users_config is not defined or
   (prezto_users_config is defined and prezto_users_config is not mapping)

- name: Install prezto from git
  git: repo={{ prezto_repo_url }}
       dest=~{{ item.key }}/.zprezto/
       track_submodules=yes
  with_dict: prezto_users_config

- name: Set to user zprezto ownership
  file:
    mode=0755
    owner={{ item.key }}
    path=~{{ item.key }}/.zprezto/
  with_dict: prezto_users_config

- name: Check if ~/.zshrc exists
  file:
    path=~{{ item.key }}/.zshrc
    state=touch
  with_dict: prezto_users_config

- name: Update .zshrc
  lineinfile:
    dest=~{{ item.key }}/.zshrc
    line="# File managed by ansible, should not be modified."
    insertbefore=BOF
    state=present
  with_dict: prezto_users_config

- name: Add line for sourcing prezto in .zshrc.
  lineinfile:
    dest=~{{ item.key }}/.zshrc
    line="\n# Source prezto \n{{ prezto_source }}"
    insertafter="# File managed by ansible, should not be modified."
    regexp="zprezto/init"
    state=present
  with_dict: prezto_users_config

- name: Set up zlogin
  template:
    mode=0744
    owner={{ item.key }}
    src=zlogin.j2
    dest=~{{ item.key }}/.zlogin
  with_dict: prezto_users_config

- name: Set up zlogout
  template:
    mode=0744
    owner={{ item.key }}
    src=zlogout.j2
    dest=~{{ item.key }}/.zlogout
  with_dict: prezto_users_config

- name: Set up zprofile
  template:
    mode=0744
    owner={{ item.key }}
    src=zprofile.j2
    dest=~{{ item.key }}/.zprofile
  with_dict: prezto_users_config

- name: Set up zpreztorc
  template:
    mode=0744
    owner={{ item.key }}
    src=zpreztorc.j2
    dest=~{{ item.key }}/.zpreztorc
  with_dict: prezto_users_config

- name: Set up zshenv
  template:
    mode=0744
    owner={{ item.key }}
    src=zshenv.j2
    dest=~{{ item.key }}/.zshenv
  with_dict: prezto_users_config
